model_type: "openvla_oft"
implement_version: "rlinf"

model_path: "/path/to/model/RLinf-OpenVLAOFT-LIBERO-130-Base-Lora"

precision: "bf16"

value_type: action_level

action_dim: 7
num_action_chunks: 8
use_proprio: False
use_film: False
unnorm_key: libero_130_no_noops_trajall
center_crop: True

max_prompt_length: 128
vocab_size: 32000
hidden_size: 4096
add_value_head: False
image_size: [224, 224]
is_lora: True
lora_rank: 32
lora_path: null
num_images_in_input: 1
attn_implementation: "flash_attention_2"
low_cpu_mem_usage: True
trust_remote_code: True
