defaults:
  - libero_cql_openvlaoft_adapter_offline

runner:
  logger:
    experiment_name: "libero_calql_openvlaoft_adapter_offline"

algorithm:
  offline_rl:
    name: calql
    calql:
      returns_to_go_gamma: 1.0
