defaults:
  - env/dataset_env_libero@env.train
  - env/dataset_env_libero@env.eval
  - model/openvla_oft@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_grpo_openvlaoft_adapter_offline"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: 250
  save_interval: 250

  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl

  group_size: 8
  rollout_epoch: 2
  eval_rollout_epoch: 1

  reward_type: action_level
  logprob_type: action_level
  entropy_type: action_level

  adv_type: grpo_per_action
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  reward_coef: 5.0

  sampling_params:
    do_sample: True
    temperature_train: 1.6
    temperature_eval: 1.6
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

  filter_rewards: False
  rewards_lower_bound: -10.0
  rewards_upper_bound: 10.0

env:
  group_name: "EnvGroup"

  train:
    data_path: "/inspire/hdd/project/chemicalreaction/zhutong-24049/wudi/dataset/pi_libero/data"
    total_num_envs: 64
    max_steps_per_rollout_epoch: 8
    max_episode_steps: 8
    reward_fn: mae
    reward_coef: ${algorithm.reward_coef}
    reward_type: ${adapter_reward.type}
    error_fn: ${adapter_reward.error_fn}
    residual_penalty: ${adapter_reward.residual_penalty}
    residual_coef: ${adapter_reward.residual_coef}
    group_size: ${algorithm.group_size}
    chunk_size: 8
  eval:
    data_path: "/inspire/hdd/project/chemicalreaction/zhutong-24049/wudi/dataset/pi_libero/data"
    total_num_envs: 8
    auto_reset: False
    ignore_terminations: False
    max_episode_steps: 8
    max_steps_per_rollout_epoch: 8
    reward_type: ${adapter_reward.type}
    error_fn: ${adapter_reward.error_fn}
    residual_penalty: ${adapter_reward.residual_penalty}
    residual_coef: ${adapter_reward.residual_coef}
    group_size: 1
    is_eval: True
    video_cfg:
      save_video: False
      info_on_video: False
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1

  model:
    model_path: "/inspire/hdd/project/chemicalreaction/zhutong-24049/wudi/model/Rlinf-OpenVLAOFT-LIBERO-130-Base-Lora"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 16
  global_batch_size: 64
  seed: 1234
  enable_offload: True

  model:
    model_path: "/inspire/hdd/project/chemicalreaction/zhutong-24049/wudi/model/Rlinf-OpenVLAOFT-LIBERO-130-Base-Lora"
    model_type: "openvla_oft"
    unnorm_key: libero_130_no_noops_trajall
    proprio_dim: 8
    max_prompt_length: 128
    adapter: ${adapter}
    vla: ${vla}

  optim:
    lr: 2.0e-5
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0

  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    use_orig_params: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False

adapter:
  enable: true
  type: residual_chunk_adapter
  hidden_dim: 512
  num_layers: 3
  use_layernorm: true
  residual_bound: 0.5
  std_mode: global_learnable
  init_log_std: -2.0

adapter_reward:
  type: absolute
  error_fn: mae
  residual_penalty: l1
  residual_coef: 0.01

vla:
  freeze_backbone: true
  freeze_action_head: true
  feature_type: pooled_last_hidden
  use_base_action: true
