defaults:
  - maniskill_sac_mlp

runner:
  logger:
    experiment_name: "cql_mlp"

algorithm:
  offline_rl:
    name: cql
    cql:
      alpha_type: exp
      initial_alpha: 1.0
      alpha_threshold: 10.0
      conservative_weight: 5.0
      n_action_samples: 10
      optim:
        lr: 1.0e-4
        lr_scheduler: torch_constant
        clip_grad: 10.0

actor:
  model:
    add_value_head: False
    add_q_head: True
